### ISSUE TITLE
可以测试一下openbuddy-deepseek-67b-v15.2

### ISSUE THREAD

**Issue by openmynet** [jeinlee1991/chinese-llm-benchmark#21]
openbuddy-deepseek-67b-v15.2在体验上不输chatgpt3.5，对于一些虚构的事实的能准确的识别出来比如一下几个例子：
1. 为什么华佗对本草纲目评价很高？
2. 为什么贝多芬看到肖邦的夜曲会很惊讶？
文心和星火直接会把你带沟里。

如果问： 黄盖为什么要打周瑜？
文心和星火直接认为你问的是： 周瑜为什么要打黄盖。

**Comment by jeinlee1991** [comment]
已加入
