### ISSUE TITLE
我们能不能增加一些基于智能体的评测

### ISSUE THREAD

**Issue by CoderYiFei** [jeinlee1991/chinese-llm-benchmark#49]
比如基于 open-interpreter  去做一些复杂的系统和软件的执行与开发
比如基于 matagpt 去做一些复杂的游戏开发
比如基于 screenshot-to-code 去测一些大模型去做页面设计的能力等等
比如互相pk完成的情况，节约了程序员多少的开发时间等等。

这些相对有一定智能体调用的测试，比前面普通的代码测试，和数学测试，要实用的多

**Comment by jeinlee1991** [comment]
很好的建议，后续会考虑加入。有需要的话，可以进微信群（详见项目主页底部），一起交流讨论。
