### ISSUE TITLE
请问下打分是如何实现的？人工打分还是代码自动打分？

### ISSUE THREAD

**Issue by dengfan2018** [jeinlee1991/chinese-llm-benchmark#52]
如信息抽取这种打分，请问下是人工评分还是有代码自动打分呢？

时间：下周二上午 10 点
地点：公司位于市中心的办公室
事件：候选人参加 XYZ 公司的面试

llm: Doubao-pro-32k
score: 3/5

**Comment by jeinlee1991** [comment]
大部分是人工打分，少部分自动打分并人工审核
